spring:
  datasource:
    url: jdbc:mysql://localhost:3306/2008-seckill
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.126.129
    password: root
  rabbitmq:
    host: 192.168.126.129
    virtual-host: my_vhost
    username: admin
    password: admin
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 50 # 该消费者最多有50个消息是等应答
        concurrency: 1 #消费者的数量
        max-concurrency: 1
logging:
  level:
    com.qf: debug
server:
  port: 8015