spring:
  rabbitmq:
    host: 192.168.126.129
    virtual-host: my_vhost
    username: admin
    password: admin
    listener:
      simple:
        acknowledge-mode: manual
  redis:
    host: 192.168.126.129
    password: root
server:
  port: 8014